### ISSUE TITLE
Could not start the phpfpmservice service on windows 10 build 18362

### ISSUE THREAD

**Issue by duncte123** [cretueusebiu/valet-windows#118]
I just updated my computer to windows 10 build 18362 and noticed that valet doesn't start anymore.

Yes I have cmd running in administrator mode
Yes the same happens in PowerShell

The only log file created is `phpfpmservice.wrapper.log` and this is its content
```
2019-05-27 18:15:05,810 INFO  - Starting ServiceWrapper in the CLI mode
2019-05-27 18:15:06,669 FATAL - WMI Operation failure: NoSuchService
WMI.WmiException: NoSuchService
   at winsw.WrapperService.ThrowNoSuchService()
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)
2019-05-27 18:15:06,814 INFO  - Starting ServiceWrapper in the CLI mode
2019-05-27 18:15:07,639 FATAL - WMI Operation failure: NoSuchService
WMI.WmiException: NoSuchService
   at winsw.WrapperService.ThrowNoSuchService()
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)
2019-05-27 18:15:09,886 INFO  - Starting ServiceWrapper in the CLI mode
2019-05-27 18:15:10,657 FATAL - WMI Operation failure: NoSuchService
WMI.WmiException: NoSuchService
   at winsw.WrapperService.ThrowNoSuchService()
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)
```

**Comment by alystair** [comment]
Oddly enough I experienced something similar, I ran `valet uninstall` and `valet install` under admin and it seemed to function.

**Comment by duncte123** [comment]
Yup, this resolved it for me as well

**Comment by alystair** [comment]
I don't think this should actually be closed as doing so is a sort of a work around for a potential bug -  @cretueusebiu what do you think?

**Comment by duncte123** [comment]
> I don't think this should actually be closed as doing so is a sort of a work around for a potential bug - @cretueusebiu what do you think?

Looks like it's a huge bug indeed as it seems that all my applications are getting timed out on nginx

**Comment by danielfowler** [comment]
I ran into this issue today, but I didn't have to uninstall. I just ran Bash as administrator and tried `valet install` again, and it worked.

**Comment by duncte123** [comment]
> I ran into this issue today, but I didn't have to uninstall. I just ran Bash as administrator and tried `valet install` again, and it worked.

Still does not fix this issue ![image](https://duncte123.one/yJHL9c9.png)

**Comment by duncte123** [comment]
Update to this: It looks like the valet_fpm service keeps restarting, killing the service and running `php-cgi -b 127.0.0.1:9001` works fine

**Comment by Leamo** [comment]
I face the same problem. How do you kill valet_fpm service exactly ?

**Comment by duncte123** [comment]
> I face the same problem. How do you kill valet_fpm service exactly?

I just killed it via task manager and started a new fpm process myself
