### ISSUE TITLE
Could not install the nginxservice service

### ISSUE THREAD

**Issue by vikas5914** [cretueusebiu/valet-windows#13]
Could not install the nginxservice service. Check ~/.valet/Log for errors.

2017-03-02 13:32:39,983 INFO  - Starting ServiceWrapper in the CLI mode
2017-03-02 13:32:40,126 FATAL - WMI Operation failure: NoSuchService
WMI.WmiException: NoSuchService
   at winsw.WrapperService.ThrowNoSuchService()
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)
2017-03-02 13:32:42,722 INFO  - Starting ServiceWrapper in the CLI mode
2017-03-02 13:32:42,867 FATAL - WMI Operation failure: NoSuchService
WMI.WmiException: NoSuchService
   at winsw.WrapperService.ThrowNoSuchService()
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)
2017-03-02 13:32:43,104 INFO  - Starting ServiceWrapper in the CLI mode
2017-03-02 13:32:43,239 INFO  - Uninstalling the service with id 'valet_nginx'
2017-03-02 13:32:43,242 WARN  - The service with id 'valet_nginx' does not exist. Nothing to uninstall
2017-03-02 13:32:43,252 INFO  - Completed. Exit code is 0
2017-03-02 13:32:43,537 INFO  - Starting ServiceWrapper in the CLI mode
2017-03-02 13:32:43,684 FATAL - WMI Operation failure: AccessDenied
WMI.WmiException: AccessDenied
   at WMI.WmiRoot.BaseHandler.CheckError(ManagementBaseObject result)
   at WMI.WmiRoot.ClassHandler.Invoke(Object proxy, MethodInfo method, Object[] args)
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)

**Comment by vikas5914** [comment]
Fixed:  i was using CMD.  with PowerShell it was successful

**Comment by qcind** [comment]
it works in PowerShell on win10 platform.

**Comment by soumyaRauth** [comment]
It does not work in PowerShell either for me.

**Comment by goowikns** [comment]
Same for me, doesn't seem to work with PowerShell either

**Comment by jartaud** [comment]
@goowikns running Git Bash as Admin works for me. Thanks!

**Comment by EdixonAlberto** [comment]
Fix it by opening the terminal in administrator mode

**Comment by mfislambd** [comment]
It works for all comand line just run as administrator  mood.

**Comment by weerdenburg** [comment]
Would it be an idea that Valet for Windows checks if it's running in admin mode? And if not... shows a nice notification/error?

**Comment by cretueusebiu** [comment]
@weerdenburg I've tried that but without success...

**Comment by weerdenburg** [comment]
@cretueusebiu That's a bummer, but have you tried for example the `net SESSION` trick?

I have implemented it with succes in some batch scripts that Visual Studio triggered after compiling.
I also needed to stop and start a service with admin privileges.

So in my case I had to run Visual Studio as administrator.

```
@echo off
net SESSION >nul 2>&1
if %ERRORLEVEL% NEQ 0 goto AdminError

echo Executing:
echo %0 %*

net STOP "serviceA"

echo Here you can do some extra logic like adjusting config files or copy some files etc...

net START "serviceA"
goto End

:AdminError
echo;
echo !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
echo It seems that you have started this batch-file (or Microsoft Visual Studio) without admin privileges.
echo !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
echo;
:End
```

**Comment by Ahmed-Aboud** [comment]
when i changed the directory to the C and valet install it worked

**Comment by Maariaah** [comment]
Same here, I could not install it on D, but when I changed to  C:\WINDOWS\system32> it installed successfully

**Comment by MeowKim** [comment]
same here. CMD or POWERSHELL as administrator was not working on D. Now it works when I changed to C :)

**Comment by ajithjojo** [comment]
hey .. open CMD  as administrator  then it will work

**Comment by BayuAriyadi** [comment]
mysql xampp 404 not fund
