### ISSUE TITLE
Valet not starting automatically

### ISSUE THREAD

**Issue by jeremybasolo** [cretueusebiu/valet-windows#14]
It doesn't seem to start automatically when my computer starts, I have to open CMD as administrator and type valet start.

**Comment by cretueusebiu** [comment]
Can you check if the services start  ? Have you looked at the logs  ?

![785edb48940a466f899c60a9d4f7d908 1](https://cloud.githubusercontent.com/assets/1517945/24081099/260be19c-0cb5-11e7-801b-16874f344b91.png)

**Comment by jeremybasolo** [comment]
Services don't start: 
![valet-screen](https://cloud.githubusercontent.com/assets/1381749/24117002/6b69f42c-0da0-11e7-8e0e-457f0add06cf.png)

phpfpmservice.wrapper.log contains the below for today:

2017-03-20 18:50:32,336 INFO  - Stopping valet_phpfpm
2017-03-20 18:50:49,350 DEBUG - ProcessKill 12664

**Comment by cretueusebiu** [comment]
Run `valet start` and check the logs again.

**Comment by jeremybasolo** [comment]
Ah yeay, some new stuff here:

2017-03-20 19:10:15,259 INFO  - Starting ServiceWrapper in the CLI mode
2017-03-20 19:10:15,946 FATAL - WMI Operation failure: ServiceCannotAcceptControl
WMI.WmiException: ServiceCannotAcceptControl
   at WMI.WmiRoot.BaseHandler.CheckError(ManagementBaseObject result)
   at WMI.WmiRoot.InstanceHandler.Invoke(Object proxy, MethodInfo method, Object[] args)
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)
2017-03-20 19:10:16,339 INFO  - Starting ServiceWrapper in the CLI mode
2017-03-20 19:10:16,668 INFO  - Starting ServiceWrapper in the service mode
2017-03-20 19:10:16,691 INFO  - Completed. Exit code is 0
2017-03-20 19:10:16,776 INFO  - Starting C:\php\php-cgi.exe -b 127.0.0.1:9000
2017-03-20 19:10:16,808 INFO  - Starting C:\php\php-cgi.exe -b 127.0.0.1:9000
2017-03-20 19:10:17,291 INFO  - Started 9532
