### ISSUE TITLE
valet_nginx won't start

### ISSUE THREAD

**Issue by cringer** [cretueusebiu/valet-windows#17]
For all purposes of installation, I'm told everything is installed.  However, when I tried to browse a test site I got the "This page cannot be found" error.  Checked the services and noticed that there were 2 new services, valet_nginx and valet_phpfpm.  Both are set to automatic but only valet_phpfpm is started.  When manually trying to start valet_nginx I get the error ``Error 1067: The process terminated unexpectedly."

I checked the event logs which list `Child process [6364 - C:\Users\jschaffer\AppData\Roaming\Composer\vendor\cretueusebiu\valet-windows\bin\nginx\nginx.exe  -p C:\Users\jschaffer\AppData\Roaming\Composer\vendor\cretueusebiu\valet-windows\bin\nginx ] finished with 1`

I checked ~/.valet/Logs but they are mostly empty with the exception of nginxservice-err.log `nginx: [emerg] bind() to 0.0.0.0:80 failed (10013: An attempt was made to access a socket in a way forbidden by its access permissions)` and ngnxservice.wrapper.log
```
2017-03-28 15:02:09,634 INFO  - Starting ServiceWrapper in the CLI mode
2017-03-28 15:02:09,829 FATAL - WMI Operation failure: ServiceCannotAcceptControl
WMI.WmiException: ServiceCannotAcceptControl
   at WMI.WmiRoot.BaseHandler.CheckError(ManagementBaseObject result)
   at WMI.WmiRoot.InstanceHandler.Invoke(Object proxy, MethodInfo method, Object[] args)
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)
2017-03-28 15:02:10,267 INFO  - Starting ServiceWrapper in the CLI mode
2017-03-28 15:02:10,464 FATAL - WMI Operation failure: ServiceCannotAcceptControl
WMI.WmiException: ServiceCannotAcceptControl
   at WMI.WmiRoot.BaseHandler.CheckError(ManagementBaseObject result)
   at WMI.WmiRoot.InstanceHandler.Invoke(Object proxy, MethodInfo method, Object[] args)
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)
2017-03-28 15:02:10,652 INFO  - Starting ServiceWrapper in the CLI mode
2017-03-28 15:02:10,933 INFO  - Starting ServiceWrapper in the service mode
2017-03-28 15:02:10,944 INFO  - Completed. Exit code is 0
2017-03-28 15:02:10,951 INFO  - Starting C:\Users\jschaffer\AppData\Roaming\Composer\vendor\cretueusebiu\valet-windows\bin\nginx\nginx.exe  -p C:\Users\jschaffer\AppData\Roaming\Composer\vendor\cretueusebiu\valet-windows\bin\nginx 
2017-03-28 15:02:10,954 INFO  - Starting C:\Users\jschaffer\AppData\Roaming\Composer\vendor\cretueusebiu\valet-windows\bin\nginx\nginx.exe  -p C:\Users\jschaffer\AppData\Roaming\Composer\vendor\cretueusebiu\valet-windows\bin\nginx 
2017-03-28 15:02:10,958 INFO  - Started 12364
```

I am running in an administrator shell and I am a local administrator to this system.  I am running Windows 10.

**Comment by cretueusebiu** [comment]
Can you check if the Acrylic service is running too ? 
![8ffe14318328411a9f9ec9858e6fd901 1](https://cloud.githubusercontent.com/assets/1517945/24444968/fc9b955a-1470-11e7-93f4-a515d28afed8.png)

Also make sure it is [configured](http://mayakron.altervista.org/wikibase/show.php?id=AcrylicWindows10Configuration). By default it will be configured when you install Valet but sometimes those settings might not be set.

**Comment by tonimitrevski** [comment]
Same problem
![valet_nginx](https://cloud.githubusercontent.com/assets/15773773/24582276/312909ca-172c-11e7-8887-870654f25e17.jpg)

**Comment by cringer** [comment]
I checked Acrylic service and it was running.  I followed the configuration guide from the link specified but it did nothing for the issue.  It did, however, break my DNS lookups.

**Comment by cretueusebiu** [comment]
@cringer And alternative is to just add each domain manually in your `hosts` file.

**Comment by cringer** [comment]
That's fine, however it doesn't solve that fact that valet_nginx wont start

**Comment by cretueusebiu** [comment]
Not sure what this could be or how to reproduce it...

**Comment by garrensweet** [comment]
@cringer  Have you figured this out? I have exactly the same problem.

**Comment by garrensweet** [comment]
@cringer I managed to solve this. I found that there was a service in windows 10 called "World Wide Web Publishing Service" that was consuming port 80. This service was controlling port 80 for me, and therefore nginx could not listen on 80, thus resulting in the failure.

Once I ended this service, I was able to restart nginx correctly and everything was fine.

@cretueusebiu for visibility.

**Comment by Ravin001** [comment]
is there a way i can change the port for ngnix. I am unable to find where the config file for the same is

**Comment by jcoszig** [comment]
`net stop W3SVC`
will stop the World Wide Web Publishing Service.
I suggest running `netstat -n -o -a | find ":80"` to check whether port 80 is occupied before and after stopping the service.

**Comment by FauziFerdiansyah** [comment]
> @cringer I managed to solve this. I found that there was a service in windows 10 called "World Wide Web Publishing Service" that was consuming port 80. This service was controlling port 80 for me, and therefore nginx could not listen on 80, thus resulting in the failure.
> 
> Once I ended this service, I was able to restart nginx correctly and everything was fine.
> 
> @cretueusebiu for visibility.

you save my sleep time 🙌🙌👍👍👍👍❤
