### ISSUE TITLE
Windows 11 Update

### ISSUE THREAD

**Issue by AndresReyesDev** [cretueusebiu/valet-windows#172]
I leave this in case anyone might find it useful:

I upgraded my Windows 10 to 11 yesterday and when I tried to access one of my developing websites (that work with Valet) it would not resolve. I tried to restart valet but got the following message:

```
C:\Users\andres> valet restart
2021-06-29 09:43:21,200 INFO  - Restarting the service with id 'valet_phpcgi'
2021-06-29 09:43:21,202 FATAL - WMI Operation failure: NoSuchService
WMI.WmiException: NoSuchService
   at WinSW.Program.ThrowNoSuchService()
   at WinSW.Program.<Run>g__Restart|2_5(<>c__DisplayClass2_0& )
   at WinSW.Program.Run(String[] argsArray, IWinSWConfiguration descriptor)
   at WinSW.Program.Main(String[] args)
WMI.WmiException: NoSuchService
   at WinSW.Program.ThrowNoSuchService()
   at WinSW.Program.<Run>g__Restart|2_5(<>c__DisplayClass2_0& )
   at WinSW.Program.Run(String[] argsArray, IWinSWConfiguration descriptor)
   at WinSW.Program.Main(String[] args)
2021-06-29 09:43:51,254 INFO  - Restarting the service with id 'valet_phpcgi'
2021-06-29 09:43:51,256 FATAL - WMI Operation failure: NoSuchService
WMI.WmiException: NoSuchService
   at WinSW.Program.ThrowNoSuchService()
   at WinSW.Program.<Run>g__Restart|2_5(<>c__DisplayClass2_0& )
   at WinSW.Program.Run(String[] argsArray, IWinSWConfiguration descriptor)
   at WinSW.Program.Main(String[] args)
WMI.WmiException: NoSuchService
   at WinSW.Program.ThrowNoSuchService()
   at WinSW.Program.<Run>g__Restart|2_5(<>c__DisplayClass2_0& )
   at WinSW.Program.Run(String[] argsArray, IWinSWConfiguration descriptor)
   at WinSW.Program.Main(String[] args)
Failed to restart service [phpcgiservice]. Check ~/.config/valet/Log for errors.
```

The problem was easily solved by reinstalling valet using the command in a console with administrative privileges:

`valet install`

Finally everything works correctly.

**Comment by cretueusebiu** [comment]
Already on Windows 11 ? 😄
Reinstalling valet is usually the fix even now for some Win 10 updates.

**Comment by AndresReyesDev** [comment]
> Already on Windows 11 ? 😄
> Reinstalling valet is usually the fix even now for some Win 10 updates.

Yes, I've installed it, I'm an early adopter and BTW... I'm a bit disappointed 😂

**Comment by MiloudiMohamed** [comment]
Thanks, this helps
