### ISSUE TITLE
problem with valet_phpfpm

### ISSUE THREAD

**Issue by Inter95** [cretueusebiu/valet-windows#8]
I installed valet in my PC on Windows 10 pro without any issue but when I try to install on my Laptop with same Windows 10 pro I get error 504.

This is what I'm getting from **nginxservice.wrapper.log**
`2017-02-05 18:13:17,832 INFO  - Starting ServiceWrapper in the CLI mode
2017-02-05 18:13:18,036 FATAL - WMI Operation failure: ServiceCannotAcceptControl
WMI.WmiException: ServiceCannotAcceptControl
   at WMI.WmiRoot.BaseHandler.CheckError(ManagementBaseObject result)
   at WMI.WmiRoot.InstanceHandler.Invoke(Object proxy, MethodInfo method, Object[] args)
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)
2017-02-05 18:13:18,442 INFO  - Starting ServiceWrapper in the CLI mode
2017-02-05 18:13:18,645 FATAL - WMI Operation failure: ServiceCannotAcceptControl`

**phpfpmservice.wrapper.log**
`2017-02-05 18:13:03,033 INFO  - Starting ServiceWrapper in the CLI mode
2017-02-05 18:13:03,221 INFO  - Completed. Exit code is 0
2017-02-05 18:13:03,596 INFO  - Starting ServiceWrapper in the CLI mode
2017-02-05 18:13:03,799 FATAL - WMI Operation failure: ServiceCannotAcceptControl
WMI.WmiException: ServiceCannotAcceptControl
   at WMI.WmiRoot.BaseHandler.CheckError(ManagementBaseObject result)
   at WMI.WmiRoot.InstanceHandler.Invoke(Object proxy, MethodInfo method, Object[] args)
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)
2017-02-05 18:13:04,002 INFO  - Starting ServiceWrapper in the CLI mode
2017-02-05 18:13:04,314 INFO  - Starting ServiceWrapper in the service mode
2017-02-05 18:13:04,330 INFO  - Completed. Exit code is 0
2017-02-05 18:13:04,346 INFO  - Starting C:\php\php-cgi.exe -b 127.0.0.1:9000
2017-02-05 18:13:04,346 INFO  - Starting C:\php\php-cgi.exe -b 127.0.0.1:9000`

**Comment by cretueusebiu** [comment]
Make sure you run it as Administrator (and have administrator permissions).

**Comment by Inter95** [comment]
I ran it as Administrator same as on my PC
